// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.1-0.20240601101045-cb61b77eea50 DO NOT EDIT.
package api

// ErrorResponseSchema defines model for ErrorResponseSchema.
type ErrorResponseSchema struct {
	Message string `json:"message"`
}
