openapi: 3.0.3
info:
  title: Sample oapi-codegen std http APP
  description: |-
    This is a sample server.
  termsOfService: https://localhost:8080
  contact:
    email: kotaro.otaka@example.com
  license:
    name: Apache 2.0
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: Health
    description: Health
paths:
  /health:
    get:
      tags:
        - Health
      summary: Health
      description: Health
      operationId: health
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseSchema"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ErrorResponseSchema:
      type: object
      properties:
        message:
          type: string
      required:
        - message
